openapi: 3.1.0
servers:
  - url: /api
info:
  version: 1.0.0
  title: Recipes
  description: An API to manage your favourite recipes
tags:
  - name: Recipe
    description: Everything about your recipes
  - name: User
    description: Everything related to the user
security:
  - cookieAuth: []
paths:
  /login:
    post:
      tags:
        - User
      security: []
      summary: Login a user
      operationId: login
      requestBody:
        description: Login a user with the provided credentials
        $ref: '#/components/requestBodies/Credentials'
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/AuthenticatedUser'
        default:
          $ref: '#/components/responses/Error'
  /logout:
    post:
      tags:
        - User
      security: []
      summary: Logout a user
      operationId: logout
      responses:
        '200':
          description: Successful operation
          headers:
            'Set-Cookie':
              $ref: '#/components/headers/SessionCookie'
        default:
          $ref: '#/components/responses/Error'
  /register:
    post:
      tags:
        - User
      security: []
      summary: Register a new user
      operationId: register
      requestBody:
        description: The new user credentials
        $ref: '#/components/requestBodies/Credentials'
      responses:
        '204':
          description: Registration was successful
        default:
          $ref: '#/components/responses/Error'
  /user/confirm:
    post:
      tags:
        - User
      security: [ ]
      summary: Confirm a user account after successful registration
      operationId: confirmUser
      requestBody:
        $ref: '#/components/requestBodies/ConfirmUser'
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/password:
    post:
      tags:
        - User
      security: [ ]
      summary: Modify a user's password based on a reset token
      operationId: updatePassword
      requestBody:
        $ref: '#/components/requestBodies/UpdatePassword'
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/password/reset:
    post:
      tags:
        - User
      security: []
      summary: Reset password for an existing user by email
      operationId: resetPassword
      requestBody:
        description: The user's email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/profile:
    get:
      tags:
        - User
      summary: Get the profile of the logged in user
      operationId: getUserProfile
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/User'
        default:
          $ref: '#/components/responses/Error'
  /recipes:
    get:
      tags:
        - Recipe
      summary: Get all recipes
      operationId: getRecipes
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/RecipeList'
        default:
          $ref: '#/components/responses/Error'
    post:
      tags:
        - Recipe
      summary: Add a new recipe to the store
      operationId: addRecipe
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
      requestBody:
        description: Create a new recipe in the store
        $ref: '#/components/requestBodies/Recipe'
  '/recipes/{recipeId}':
    get:
      tags:
        - Recipe
      summary: Find a recipe by ID
      description: Returns a single recipe
      operationId: getRecipeById
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
    post:
      tags:
        - Recipe
      summary: Updates a recipe in the store
      description: ''
      operationId: updateRecipe
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        $ref: '#/components/requestBodies/Recipe'
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
    delete:
      tags:
        - Recipe
      summary: Deletes a recipe
      description: ''
      operationId: deleteRecipe
      parameters:
        - name: recipeId
          in: path
          description: Recipe ID to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        default:
          $ref: '#/components/responses/Error'
components:
  headers:
    SessionCookie:
      description: Sets the session for the logged in user
      schema:
        type: string
        examples:
          - SESSID=123; Path=/; HttpOnly
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSID
  schemas:
    Credentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          examples:
            - test@example.com
        password:
          type: string
          examples:
            - Spaghetti Carbonara
    Error:
      type: object
      description: Represents an error
      properties:
        code:
          type: integer
          examples:
            - 1
        message:
          type: string
      required:
        - code
        - message
    RecipeStatus:
      type: string
      description: Recipe status in the store
      enum:
        - available
        - pending
        - sold
    WriteRecipe:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          examples:
            - Spaghetti Carbonara
    ReadRecipe:
      allOf:
        - $ref: '#/components/schemas/WriteRecipe'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              examples:
                - 10
    ReadUser:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 10
        email:
          type: string
          examples:
            - user@example.com
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          examples:
            - abd87ec862b6b8ecc2cf45c170d887d21e835a35f8537ea35ff1af102faa5920
    UpdatePassword:
      allOf:
        - $ref: '#/components/schemas/Token'
        - type: object
          required:
            - password
          properties:
            password:
              type: string
              examples:
                - my new password
  requestBodies:
    Credentials:
      description: User credentials
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Credentials'
    Recipe:
      description: Recipe object that needs to be added to the store
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WriteRecipe'
    UpdatePassword:
      description: The user's new password as well as the required reset token
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdatePassword'
    ConfirmUser:
      description: The user's new password as well as the required reset token
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Token'
  responses:
    Error:
      description: Something went wrong
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    AuthenticatedUser:
      description: User object returned as result
      headers:
        'Set-Cookie':
          $ref: '#/components/headers/SessionCookie'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadUser'
    RecipeList:
      description: Recipe object returned as result
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ReadRecipe'
    Recipe:
      description: Recipe object returned as result
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadRecipe'
    User:
      description: User object returned as result
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadUser'